### ISSUE TITLE
gridshell design issue

### ISSUE THREAD

**Issue by han-so1omon** [EmilPoulsen/Emu.Resources#3]
what does it mean for solid box cross-section to be 0.5x0.5[m]. Does this mean that the wood beams are 0.5m thick? If so then why are they so thick? Perhaps this is meant to be mm and is a typo, as the default lengths of gridpoints are 1mm apart.

**Comment by han-so1omon** [comment]
Is there a way to bias solution range so that the grid pops up?

**Comment by han-so1omon** [comment]
Is there a way to bias solution range so that the grid pops up?

**Comment by EmilPoulsen** [comment]
@han-so1omon Thanks for the feedback. Yes, all units should be expressed in SI units.

> Is there a way to bias solution range so that the grid pops up?

You can apply a point load in the middle of the grid. Have a look at the [ElasticGridshellFormation example](https://github.com/EmilPoulsen/Emu.Resources/tree/master/examples/ElasticGridshellFormation).
